apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fsl-challenge
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: fsl-challenge.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fsl-challeng
            port:
              number: 8080